/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../src/push-notifications.module';
import * as import2 from '../../src/push-notifications.service';
class PushNotificationsModuleInjector extends import0.ɵNgModuleInjector<import1.PushNotificationsModule> {
  _PushNotificationsModule_0:import1.PushNotificationsModule;
  __PushNotificationsService_1:import2.PushNotificationsService;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _PushNotificationsService_1():import2.PushNotificationsService {
    if ((this.__PushNotificationsService_1 == null)) { (this.__PushNotificationsService_1 = new import2.PushNotificationsService()); }
    return this.__PushNotificationsService_1;
  }
  createInternal():import1.PushNotificationsModule {
    this._PushNotificationsModule_0 = new import1.PushNotificationsModule();
    return this._PushNotificationsModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.PushNotificationsModule)) { return this._PushNotificationsModule_0; }
    if ((token === import2.PushNotificationsService)) { return this._PushNotificationsService_1; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const PushNotificationsModuleNgFactory:import0.NgModuleFactory<import1.PushNotificationsModule> = new import0.NgModuleFactory<any>(PushNotificationsModuleInjector,import1.PushNotificationsModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvZmF0ZW4vRG9jdW1lbnRzL05vYmxlIGNvZGUvYW5ndWxhcjItbm90aWZpY2F0aW9ucy9zcmMvcHVzaC1ub3RpZmljYXRpb25zLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9mYXRlbi9Eb2N1bWVudHMvTm9ibGUgY29kZS9hbmd1bGFyMi1ub3RpZmljYXRpb25zL3NyYy9wdXNoLW5vdGlmaWNhdGlvbnMubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
