/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../src/push-notifications.module';
import * as import2 from '../../src/push-notifications.service';
class PushNotificationsModuleInjector extends import0.ɵNgModuleInjector<import1.PushNotificationsModule> {
  _PushNotificationsModule_0:import1.PushNotificationsModule;
  __PushNotificationsService_1:import2.PushNotificationsService;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _PushNotificationsService_1():import2.PushNotificationsService {
    if ((this.__PushNotificationsService_1 == null)) { (this.__PushNotificationsService_1 = new import2.PushNotificationsService()); }
    return this.__PushNotificationsService_1;
  }
  createInternal():import1.PushNotificationsModule {
    this._PushNotificationsModule_0 = new import1.PushNotificationsModule();
    return this._PushNotificationsModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.PushNotificationsModule)) { return this._PushNotificationsModule_0; }
    if ((token === import2.PushNotificationsService)) { return this._PushNotificationsService_1; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const PushNotificationsModuleNgFactory:import0.NgModuleFactory<import1.PushNotificationsModule> = new import0.NgModuleFactory<any>(PushNotificationsModuleInjector,import1.PushNotificationsModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvYWxleG5pa2kvTm9ibGVjb2RlL2FuZ3VsYXIyLW5vdGlmaWNhdGlvbnMvc3JjL3B1c2gtbm90aWZpY2F0aW9ucy5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9hbGV4bmlraS9Ob2JsZWNvZGUvYW5ndWxhcjItbm90aWZpY2F0aW9ucy9zcmMvcHVzaC1ub3RpZmljYXRpb25zLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
