import { OnInit, OnDestroy, NgZone } from '@angular/core';
import { Notification } from './notification.type';
import { NotificationsService } from './notifications.service';
export declare class NotificationComponent implements OnInit, OnDestroy {
    private notificationService;
    private zone;
    timeOut: number;
    showProgressBar: boolean;
    pauseOnHover: boolean;
    clickToClose: boolean;
    theClass: string[];
    animate: string;
    position: number;
    item: Notification;
    progressWidth: number;
    private stopTime;
    private timer;
    private steps;
    private speed;
    private count;
    private start;
    private diff;
    constructor(notificationService: NotificationsService, zone: NgZone);
    ngOnInit(): void;
    startTimeOut(): void;
    onEnter(): void;
    onLeave(): void;
    setPosition(): number;
    onClick($e: MouseEvent): void;
    attachOverrides(): void;
    ngOnDestroy(): void;
    private instance;
    remove(): void;
}
